"""no propic

Revision ID: bd186284fcf5
Revises: 6f77ba56f99f
Create Date: 2017-12-12 13:06:45.671866

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd186284fcf5'
down_revision = '6f77ba56f99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_pro_pic_key', 'users', type_='unique')
    op.drop_column('users', 'pro_pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_pic', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_pro_pic_key', 'users', ['pro_pic'])
    # ### end Alembic commands ###
