"""user model updates

Revision ID: d93a99bd913c
Revises: 
Create Date: 2017-12-15 23:40:20.237124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd93a99bd913c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_pro_pic_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_pro_pic_key', 'users', ['pro_pic'])
    # ### end Alembic commands ###
