"""back againg

Revision ID: db8d9eebe0cd
Revises: bd186284fcf5
Create Date: 2017-12-12 13:07:51.503253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8d9eebe0cd'
down_revision = 'bd186284fcf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pro_pic', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'users', ['pro_pic'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'pro_pic')
    # ### end Alembic commands ###
